delete from Part_Ref;
delete from House;
delete from House_Creator;
delete from Part;
insert into Part (id, name, type) values ('01', 'Brick', 'WALL');
insert into Part (id, name, type) values ('02', 'Aerocrete', 'WALL');
insert into Part (id, name, type) values ('03', 'Wood', 'WALL');
insert into Part (id, name, type) values ('04', 'Metal tile', 'ROOF');
insert into Part (id, name, type) values ('05', 'Flexible roof tiles', 'ROOF');
insert into Part (id, name, type) values ('06', 'Strip', 'FOUNDATION');
insert into Part (id, name, type) values ('07', 'Pile', 'FOUNDATION');
insert into Part (id, name, type) values ('08', 'One', 'FLOOR');
insert into Part (id, name, type) values ('09', 'Two', 'FLOOR');
insert into Part (id, name, type) values ('10', 'Panoramic glazing', 'WINDOW');
insert into Part (id, name, type) values ('11', 'Energy-efficient glazing', 'WINDOW');
insert into Part (id, name, type) values ('12', 'Second light', 'WINDOW');
insert into Part (id, name, type) values ('13', 'Without balcony', 'BALCONY');
insert into Part (id, name, type) values ('14', 'Glazed', 'BALCONY');
insert into Part (id, name, type) values ('15', 'Unglazed', 'BALCONY');